services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
    -  9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
    - ./grafana:/var/lib/grafana
    ports:
    - 3000:3000

  node-ex:
    image: prom/node-exporter:latest
    container_name: node-ex
    restart: unless-stopped
    volumes:
    - /:/host:ro,rslave
    command:
    - '--path.rootfs=/host'
    ports:
    - 9100:9100
