global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.16.3.52:9090']


  - job_name: 'WEB1'
    static_configs:
    - targets: ['172.16.3.51:9100']

  - job_name: 'WEB2'
    static_configs:
    - targets: ['172.16.3.52:9100']

  - job_name: 'DB'
    static_configs:
    - targets: ['172.16.3.53:9100']

  - job_name: 'Nextcloud'
    static_configs:
    - targets: ['172.16.3.54:9100']

  - job_name: 'NAS'
    static_configs:
    - targets: ['172.16.3.55:9100']
